/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obține coșul curent al utilizatorului */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** Golește coșul utilizatorului */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Fără conținut */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adaugă o variantă de produs în coș (sau crește cantitatea) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        productVariantId: number;
                        /** @default 1 */
                        quantity?: number;
                    };
                };
            };
            responses: {
                /** @description Creat */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Date invalide */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Varianta nu a fost găsită */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Elimină un item din coș */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    itemId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Fără conținut */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Item-ul nu a fost găsit */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Actualizează cantitatea unui item din coș */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    itemId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        quantity: number;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Cantitate invalidă */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Item-ul nu a fost găsit */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuthRegisterRequest"];
                };
            };
            responses: {
                /** @description User created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Invalid input or account already exists */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuthLoginRequest"];
                };
            };
            responses: {
                /** @description Login successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Missing credentials / invalid email */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Token refreshed successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Missing, invalid or expired refresh token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returnează utilizatorul autentificat */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logout successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogoutResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/browse/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Filtrează și sortează produsele
         * @description Endpoint principal pentru filtrarea produselor (price sortează după minPrice)
         */
        get: {
            parameters: {
                query?: {
                    /** @description Căutare în nume și descriere */
                    q?: string;
                    /**
                     * @description Slug-ul categoriei
                     * @example pizza-clasice
                     */
                    categorySlug?: string;
                    /** @description Preț minim (pe minPrice) */
                    priceMin?: number;
                    /** @description Preț maxim (pe minPrice) */
                    priceMax?: number;
                    /**
                     * @description CSV sau flags[]=a&flags[]=b
                     * @example spicy,vegetarian
                     */
                    flags?: string;
                    /**
                     * @description CSV sau ingredients[]=a&ingredients[]=b
                     * @example mozzarella,tomato
                     */
                    ingredients?: string;
                    /**
                     * @description Tip aluat (cheie)
                     * @example clasic
                     */
                    dough?: string;
                    /**
                     * @description Mărime (cheie)
                     * @example medie
                     */
                    size?: string;
                    /** @description Doar produse personalizabile */
                    isCustomizable?: boolean;
                    /** @description releasedAt în ultimele `newerThanDays` zile (implicit 30) */
                    isNew?: boolean;
                    newerThanDays?: number;
                    sort?: "price" | "rating" | "popularity" | "newest";
                    order?: "asc" | "desc";
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista filtrată de produse */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BrowseResponse"];
                    };
                };
                /** @description Parametri invalizi */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Eroare internă a serverului */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/browse/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obține opțiunile de filtrare disponibile
         * @description Fără `categorySlug` → **filtre globale**; cu `categorySlug` → **filtre contextuale** (ținând cont de ceilalți parametri). Counts sunt calculate în contextul filtrării curente.
         *
         */
        get: {
            parameters: {
                query?: {
                    q?: string;
                    /** @example pizza-clasice */
                    categorySlug?: string;
                    priceMin?: number;
                    priceMax?: number;
                    /** @description CSV sau flags[]=a&flags[]=b */
                    flags?: string;
                    /** @description CSV sau ingredients[]=a&ingredients[]=b */
                    ingredients?: string;
                    dough?: string;
                    size?: string;
                    isCustomizable?: boolean;
                    isNew?: boolean;
                    newerThanDays?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Opțiunile de filtrare */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: {
                                flags?: {
                                    key?: string;
                                    label?: string;
                                    count?: number;
                                }[];
                                ingredients?: {
                                    key?: string;
                                    label?: string;
                                    count?: number;
                                }[];
                                doughTypes?: {
                                    key?: string;
                                    label?: string;
                                    count?: number;
                                }[];
                                sizeOptions?: {
                                    key?: string;
                                    label?: string;
                                    count?: number;
                                }[];
                                price?: {
                                    min?: number;
                                    max?: number;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obține toate categoriile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista categoriilor */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: components["schemas"]["Category"][];
                        };
                    };
                };
                /** @description Eroare internă */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obține o categorie după slug */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Categoria găsită */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Category"];
                        };
                    };
                };
                /** @description Slug invalid */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Categoria nu a fost găsită */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obține toate produsele (endpoint simplu) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista cu toate produsele */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductListResponse"];
                    };
                };
                /** @description Eroare internă */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/facets/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obține valorile posibile (facets) pentru filtrele unei categorii (după slug) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: Record<string, never>;
                        };
                    };
                };
                /** @description Slug invalid */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Eroare internă */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxonomies/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listează ingredientele disponibile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["Ingredient"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxonomies/flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listează flagurile disponibile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["Flag"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxonomies/dough-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listează tipurile de aluat disponibile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["DoughType"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxonomies/size-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listează opțiunile de mărime disponibile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            data?: components["schemas"]["SizeOption"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserDTO: {
            /** @example 1 */
            id: number;
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example Ion Popescu */
            name?: string;
        };
        AuthResponse: {
            user?: components["schemas"]["UserDTO"];
        };
        LogoutResponse: {
            /** @example Logged out */
            message?: string;
        };
        /** @example {
         *       "email": "user@example.com",
         *       "password": "secret123",
         *       "name": "Ion"
         *     } */
        AuthRegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            name?: string;
        };
        /** @example {
         *       "email": "user@example.com",
         *       "password": "secret123"
         *     } */
        AuthLoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        ErrorResponse: {
            /** @example Eroare de validare */
            error?: string;
            details?: {
                field?: string;
                message?: string;
            }[];
        };
        Category: {
            /** @example 1 */
            id?: number;
            /** @example pizza-clasice */
            slug?: string;
            /** @example Pizza Clasice */
            name: string;
            /** @example Pizza tradiționale cu rețete clasice italiene */
            description?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Ingredient: {
            /** @example mozzarella */
            key: string;
            /** @example Mozzarella */
            label?: string;
        };
        Flag: {
            /** @example vegetarian */
            key: string;
            /** @example Vegetarian */
            label?: string;
        };
        DoughType: {
            /** @example clasic */
            key: string;
            /** @example Aluat Clasic */
            label?: string;
        };
        SizeOption: {
            /** @example medie */
            key: string;
            /** @example Medie (30cm) */
            label?: string;
        };
        Product: {
            /** @example 1 */
            id?: number;
            /** @example Pizza Margherita */
            name: string;
            /** @example Pizza clasică italiană cu sos de roșii */
            description?: string;
            /**
             * Format: double
             * @example 25
             */
            basePrice: number;
            /**
             * Format: double
             * @example 20
             */
            minPrice?: number;
            /**
             * Format: double
             * @example 35
             */
            maxPrice?: number;
            /** @example https://cdn.example.com/pizzas/margherita.jpg */
            imageUrl?: string;
            /** @example 95 */
            popularity?: number;
            /**
             * Format: double
             * @example 4.8
             */
            ratingAverage?: number;
            /** @example 150 */
            ratingCount?: number;
            /** @example true */
            isCustomizable?: boolean;
            /** Format: date-time */
            releasedAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            category?: {
                /** @example 1 */
                id?: number;
                /** @example Pizza Clasice */
                name?: string;
                /** @example pizza-clasice */
                slug?: string;
            };
        };
        ProductWithRelations: components["schemas"]["Product"] & {
            flags?: components["schemas"]["Flag"][];
            ingredients?: components["schemas"]["Ingredient"][];
            variants?: {
                /** @example 101 */
                id?: number;
                /**
                 * Format: double
                 * @example 399
                 */
                price?: number;
                /** @example true */
                isDefault?: boolean;
                doughType?: components["schemas"]["DoughType"];
                sizeOption?: components["schemas"]["SizeOption"];
            }[];
        };
        ProductResponse: {
            /** @example Produsul a fost creat cu succes */
            message?: string;
            data?: components["schemas"]["ProductWithRelations"];
        };
        ProductListResponse: {
            /** @example Produsele au fost obținute cu succes */
            message?: string;
            data?: components["schemas"]["ProductWithRelations"][];
            /** @example 2 */
            count?: number;
        };
        BrowseResponse: {
            message?: string;
            data?: components["schemas"]["ProductWithRelations"][];
            pagination?: {
                /** @example 1 */
                page?: number;
                /** @example 12 */
                limit?: number;
                /** @example 65 */
                total?: number;
                /** @example 6 */
                totalPages?: number;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
